### ISSUE TITLE
[S2 - PBI12] Membuat laman profil User

### ISSUE THREAD

**Issue by y-andella** [SI-RPL-2022/SI4303_A_LIVEQUALIE#11]
laman profil user digunakan user untuk menampilkan profil masing-masing

**Comment by y-andella** [comment]
Berikut merupakan activity diagram dari laman forum :
![ActivityProfileUser drawio](https://user-images.githubusercontent.com/92220462/165123511-154ab8e5-f873-4c11-8295-e6f6c6154a83.png)


Usecase Description:
![image](https://user-images.githubusercontent.com/92220462/165124314-60c554c5-ca79-4f6f-acb4-a5d018829ab8.png)


Mockup:
![USER PROFIL](https://user-images.githubusercontent.com/92220462/165125003-20cbf3ae-af5d-4208-823c-141e14a1650a.png)

![USER PROFIL-1](https://user-images.githubusercontent.com/92220462/165125044-929a1f5e-e5b4-4854-a315-f9ac2ce0c070.png)

![USER PROFIL-2](https://user-images.githubusercontent.com/92220462/165125085-eb511cd0-b7c5-4d8e-ae9a-a35f0a80f12f.png)

**Comment by ekkynovrizalam** [comment]
ditambahkan untuk bisa upload photo

**Comment by HilalArqaan** [comment]
https://user-images.githubusercontent.com/92212197/170886173-182aaf0b-b38b-42c5-9df5-3610a731e9b1.mp4

Video demo [S2 - PBI12]
