### ISSUE TITLE
[S2 - PBI11] Membuat laman video Admin

### ISSUE THREAD

**Issue by y-andella** [SI-RPL-2022/SI4303_A_LIVEQUALIE#14]
laman video Admin digunakan oleh Admin untuk mengelola konten video yang ingin ditampilkan pada website

**Comment by y-andella** [comment]
Berikut merupakan activity diagram dari laman video Admin :
![ActivityShortMovieAdmin drawio](https://user-images.githubusercontent.com/92220462/165125806-4955a91e-6948-43a8-83eb-392c413c28ef.png)


Usecase Description:
![image](https://user-images.githubusercontent.com/92220462/165126168-882a0ae4-521e-4e15-bbf3-897adaff4ec5.png)

Mockup:
![Video Admin](https://user-images.githubusercontent.com/92220462/165126436-ecb521e8-ca3a-4716-978e-8bb645749ed5.png)

![Video Admin confirmation](https://user-images.githubusercontent.com/92220462/165126566-cc3030f8-d46f-4cae-9fc8-248a0e0ce6b9.png)

![Video Admin edit](https://user-images.githubusercontent.com/92220462/165126592-bcf4e23a-802e-4853-a029-3612b2b29d71.png)

**Comment by ekkynovrizalam** [comment]
Harus bisa CRUD

**Comment by y-andella** [comment]
https://user-images.githubusercontent.com/92220462/170889491-251cac91-e4e1-4937-9982-6a8c52bcedef.mp4

Video Demo S2 - PBI11 Membuat laman video admin
