### ISSUE TITLE
[S2 - PBI10] Membuat laman video User

### ISSUE THREAD

**Issue by y-andella** [SI-RPL-2022/SI4303_A_LIVEQUALIE#15]
Laman video user digunakan oleh user untuk dapat melihat video

**Comment by y-andella** [comment]
Berikut merupakan activity diagram dari laman video User :
![ActivityShortMovieUser drawio](https://user-images.githubusercontent.com/92220462/165126979-0a06efdc-93bb-4a27-ad1f-05dd6ed0e905.png)


Usecase Description:
![image](https://user-images.githubusercontent.com/92220462/165127038-2af40574-66f3-4ff6-a138-6c4dd62811fd.png)


Mockup:
![Video User](https://user-images.githubusercontent.com/92220462/165127101-8d807f7c-21e8-4281-8340-e667f4dcf32e.png)

**Comment by ekkynovrizalam** [comment]
bagian bawah merupakan list content yang diambil dari database.

**Comment by cnchaula** [comment]
Video demo [S2-PBI10] Membuat laman video user

https://user-images.githubusercontent.com/92134925/170886900-e0012e49-97af-4454-8e51-bb7215bfefac.mp4
