### ISSUE TITLE
[S2 - PBI16] Membuat laman glosarium admin

### ISSUE THREAD

**Issue by ftk2000** [SI-RPL-2022/SI4303_A_LIVEQUALIE#16]
Laman untuk mengelola daftar kosakata dari sisi admin

**Comment by ekkynovrizalam** [comment]
bisa CRUD

**Comment by ftk2000** [comment]
Activity Diagram
![Mengelola Glosarium](https://user-images.githubusercontent.com/92095441/165205268-3dc8ff29-c4d6-4408-b6b8-33347ef71b8b.jpg)

Usecase Description
![image](https://user-images.githubusercontent.com/92095441/165205431-718aac58-d87e-4562-96e6-bdad00f1a2a3.png)

Mockup
![Glossary Admin](https://user-images.githubusercontent.com/92095441/165205495-06f59f4a-5e19-49af-8c45-f3273e94a1f1.jpg)

**Comment by Yukkine** [comment]
Demo Video:

Uploading glosarium admin.mp4…

**Comment by Yukkine** [comment]
Demo Video:

https://user-images.githubusercontent.com/70952817/170887140-3aabbebe-ee9e-4db5-8193-13689afbed4b.mp4
