### ISSUE TITLE
[S3-PBI18] Membuat kolom search

### ISSUE THREAD

**Issue by Yukkine** [SI-RPL-2022/SI4303_A_LIVEQUALIE#17]
Fitur ini berguna untuk mencari konten secara keseleruhan melalui kolom search

**Comment by Larasrn** [comment]
Mockup
![Screenshot (467)](https://user-images.githubusercontent.com/92219856/174639546-a5f43c81-f627-4ce6-94a2-44092a32a5cf.png)
Video Demo S3 - PBI18 Membuat kolom search

https://user-images.githubusercontent.com/92219856/174639987-3194da76-be27-44ea-8f40-c1ffd0995e71.mp4
