### ISSUE TITLE
[S3 - PBI14] Mengelola quiz Admin

### ISSUE THREAD

**Issue by Yukkine** [SI-RPL-2022/SI4303_A_LIVEQUALIE#19]
Berguna untuk mengelola quiz yang dapat dikerjakan oleh user

**Comment by ftk2000** [comment]
Usecase Description
![image](https://user-images.githubusercontent.com/92095441/172279475-b9fc6768-9d97-473f-bac3-319d359b0448.png)

Mockup
![Quiz Admin](https://user-images.githubusercontent.com/92095441/172278873-e2e3d683-1f2e-4d58-8677-8731dfd5420f.jpg)
![Add Soal](https://user-images.githubusercontent.com/92095441/172278898-2b4a7603-e9a6-4b1b-8e9c-da1b5f65ab17.jpg)
![Edit Soal](https://user-images.githubusercontent.com/92095441/172278909-e026c9c4-dcab-4719-909a-d6cb73408cb4.jpg)
![Delete Quiz Confirmation](https://user-images.githubusercontent.com/92095441/172278915-797ab160-72fc-4c15-8480-c47905e3ca31.jpg)

**Comment by HilalArqaan** [comment]
[S3 - PBI14] Mengelola quiz Admin

https://user-images.githubusercontent.com/92212197/174623365-e819d06f-9710-4121-a23c-a1dfae6a7f17.mp4
