### ISSUE TITLE
[S3 - PBI13] Mengisi quiz User

### ISSUE THREAD

**Issue by Yukkine** [SI-RPL-2022/SI4303_A_LIVEQUALIE#20]
User dapat mengerjakan quiz yang telah diberikan admin dan dapat melihat nilai setelah mengerjakan quiz tersebut

**Comment by ftk2000** [comment]
Usecase Description
![image](https://user-images.githubusercontent.com/92095441/172279431-9404ee23-3bc3-4cab-859e-0c700c3c6ea7.png)

Mockup
![Quiz User](https://user-images.githubusercontent.com/92095441/172279210-f853bfe7-3165-40b8-a263-dae72420bf4f.jpg)

**Comment by cnchaula** [comment]
Video demo [S3 - PBI13] Mengisi quiz User

https://user-images.githubusercontent.com/92134925/174628553-7e91a487-bcea-4cb2-bdd6-591c4bb4c8d9.mp4
