### ISSUE TITLE
[S3 - PBI17] Membuat laman about us user

### ISSUE THREAD

**Issue by Yukkine** [SI-RPL-2022/SI4303_A_LIVEQUALIE#21]
Berisikan tentang about us

**Comment by ftk2000** [comment]
Activity Diagram: 
![Mengakses about us](https://user-images.githubusercontent.com/92095441/172278390-8fbf3c33-c109-4855-9c5d-c3e3ee9d1375.jpg)

Usecase Description
![image](https://user-images.githubusercontent.com/92095441/172278454-ed2239bb-f6e0-455a-804b-013e8b328092.png)

Mockup
![About Us](https://user-images.githubusercontent.com/92095441/172278495-ac9f6842-3f2d-4b7f-a25c-4e55acee7a4e.jpg)

**Comment by ekkynovrizalam** [comment]
ditambahkan fitur update konten dari sisi admin

**Comment by Yukkine** [comment]
Demonstrasi :

https://user-images.githubusercontent.com/70952817/174871063-79ec0091-d839-4815-a538-e3866b0d54a4.mp4
