### ISSUE TITLE
[S3 - PBI15] Membuat laman glosarium user

### ISSUE THREAD

**Issue by Yukkine** [SI-RPL-2022/SI4303_A_LIVEQUALIE#22]
Berisikan tentang glosarium yang dapat dilihat oleh user

**Comment by ftk2000** [comment]
Activity Diagram
![Mengakses Glosarium](https://user-images.githubusercontent.com/92095441/172278576-f6e243a9-3adf-46da-9c97-b9d6f6096593.jpg)

Usecase Description
![image](https://user-images.githubusercontent.com/92095441/172278620-6b5414cf-d339-47f2-baa2-e26a01164a2e.png)

Mockup
![Glossary User](https://user-images.githubusercontent.com/92095441/172278687-cc84f402-4cee-42ea-88e5-e110a7576317.jpg)

**Comment by y-andella** [comment]
Video Demo S3 - PBI15 Membuat laman glosarium user

https://user-images.githubusercontent.com/92220462/174625022-fde73392-b14d-4867-9e02-3161e1be205c.mp4
