### ISSUE TITLE
[S1 - PBI1] View laman artikel user

### ISSUE THREAD

**Issue by HilalArqaan** [SI-RPL-2022/SI4303_A_LIVEQUALIE#3]
saya sebagai user ingin melihat laman artikel user agar bisa mendapatkan informasi dari artikel ini

**Comment by HilalArqaan** [comment]
Diagram activity melihat laman artikel:

![diagram activity fitur artikel drawio (2)](https://user-images.githubusercontent.com/92212197/159882856-2fcbbbad-c2b4-4436-af40-cd23939b8e44.png)

Deskripsi:
![WhatsApp Image 2022-03-29 at 00 01 02 (1)](https://user-images.githubusercontent.com/92212197/160450469-31f8740a-3a4e-4514-8cd5-0ba9e5144804.jpeg)




Article User

![Article User (2)](https://user-images.githubusercontent.com/92212197/160233781-a64f8e52-201c-47f5-8a1b-4a20a96e4a6a.png)
![Article User Detail](https://user-images.githubusercontent.com/92212197/160634749-c5b6a3c5-7d8d-47d6-941d-f5813621146e.png)

**Comment by ekkynovrizalam** [comment]
1. tidak ada usecase description

2.acitivity diagram masih salah

**Comment by ekkynovrizalam** [comment]
tambahan detail sesuai arahan saya tadi. Bisa view detail artikelnya dan bisa view list per kategori ataupun keseluruhan

**Comment by cnchaula** [comment]
https://user-images.githubusercontent.com/92134925/163795578-14adee7a-e9d6-47d6-badc-264786a224e6.mp4


Video demonstrasi PBI1 View laman artikel user.
