### ISSUE TITLE
[S1 - PBI2] Membuat laman artikel Admin

### ISSUE THREAD

**Issue by HilalArqaan** [SI-RPL-2022/SI4303_A_LIVEQUALIE#4]
Saya sebagai admin ingin mengelola artikel agar artikel ini dapat dibaca oleh user

**Comment by HilalArqaan** [comment]
Admin mengelola laman artikel:
![revisi diagram activity laman artikel admin drawio (4)](https://user-images.githubusercontent.com/92212197/160650950-68dd5935-a612-445d-b1cb-5894b7bcb1d6.png)

![revisi diagram activity laman artikel admin drawio (1)](https://user-images.githubusercontent.com/92212197/160517935-7c7c411e-37bb-4d30-b106-9c89bf0bd957.png)
![revisi diagram activity laman artikel admin drawio (2)](https://user-images.githubusercontent.com/92212197/160517947-1c058fbe-6b40-4d90-85c5-bd456f883b58.png)
![revisi diagram activity laman artikel admin drawio (3)](https://user-images.githubusercontent.com/92212197/160517954-2a522d32-227d-4a04-8e88-d8432cef4ce5.png)


Deskripsi:
![WhatsApp Image 2022-03-29 at 09 39 58](https://user-images.githubusercontent.com/92212197/160523161-0bb9975b-ca43-4b09-8b8c-60911e6ba875.jpeg)
![WhatsApp Image 2022-03-29 at 09 39 40](https://user-images.githubusercontent.com/92212197/160523173-93e100bd-b9f5-49f7-b891-920c189a7fbf.jpeg)
![WhatsApp Image 2022-03-29 at 09 39 25](https://user-images.githubusercontent.com/92212197/160523179-7fe6fe4a-b222-4648-91cc-67657d584eb3.jpeg)
![WhatsApp Image 2022-03-29 at 09 39 10](https://user-images.githubusercontent.com/92212197/160523188-69e8727f-c024-4d42-bf57-232e27f6f87c.jpeg)



Article Admin
![Article Admin (4)](https://user-images.githubusercontent.com/92212197/160657267-f36c398d-882f-4555-8367-a5fe39b30c83.png)
![Edit Article Admin](https://user-images.githubusercontent.com/92212197/160657289-ad6864ae-22cf-4362-bed2-8a67f9b88472.png)
![Add Article Admin (1)](https://user-images.githubusercontent.com/92212197/160657303-c4663cc1-7c5f-42aa-a416-1683060e10dc.png)

**Comment by ekkynovrizalam** [comment]
1. tidak ada usecase description

2.acitivity diagram masih salah

**Comment by ekkynovrizalam** [comment]
ditambahkan detail mockup nya dan revisi bagian activity diagram

**Comment by cnchaula** [comment]
https://user-images.githubusercontent.com/92134925/163795314-651349ae-7a4f-4817-b4e2-3805e038f4db.mp4


Video demonstrasi PBI2 Membuat laman artikel Admin
