### ISSUE TITLE
[S1 - PBI3] Membuat login dan registrasi

### ISSUE THREAD

**Issue by HilalArqaan** [SI-RPL-2022/SI4303_A_LIVEQUALIE#5]
Saya sebagai user dan admin ingin melakukan login dan registrasi agar dapat mengakses fitur yang ada

**Comment by HilalArqaan** [comment]
Admin atau user melakukan login dan registrasi:
![diagram activity drawio (1)](https://user-images.githubusercontent.com/92212197/159882574-325a6381-a092-443c-a9d2-89d618bddc11.png)

Deskripsi:
![WhatsApp Image 2022-03-29 at 00 02 41](https://user-images.githubusercontent.com/92212197/160450341-bea260f9-c47c-4cd5-a0a6-a929b903f148.jpeg)




mock up login
![Login](https://user-images.githubusercontent.com/92212197/160229286-2e9e80ab-9db1-495b-a39e-f13fa6dda042.png)

mock up register
![Register](https://user-images.githubusercontent.com/92212197/160229362-e3da4711-bfc4-4d16-9d3a-c5b3fb441072.png)

**Comment by ekkynovrizalam** [comment]
1. tidak ada usecase description

2.acitivity diagram masih salah 

3. Bagus sudah ada mockup nya

**Comment by ekkynovrizalam** [comment]
Controllernya belum selesai

**Comment by ekkynovrizalam** [comment]
sorry salah status

**Comment by ftk2000** [comment]
https://user-images.githubusercontent.com/92095441/163794888-cd5324ef-e4dc-4587-b973-1dee733b6ddb.mp4

Video Demonstrasi PBI3 untuk user biasa

**Comment by ftk2000** [comment]
https://user-images.githubusercontent.com/92095441/163795627-9871d71d-b627-493e-a5a2-a66fed0eda7d.mp4

Video Demonstrasi PBI3 untuk admin (akun sudah dibuatkan sebelumnya)
