### ISSUE TITLE
[S1-PBI4] Laman utama forum

### ISSUE THREAD

**Issue by Yukkine** [SI-RPL-2022/SI4303_A_LIVEQUALIE#6]
Laman utama forum untuk melihat semua konten forum.

**Comment by Yukkine** [comment]
Berikut merupakan activity diagram dari laman forum :
![Laman Utama Forum](https://user-images.githubusercontent.com/70952817/160516129-cf010590-9de5-4c7e-a1ab-dfab2fdc092a.png)

Usecase Description:
![image](https://user-images.githubusercontent.com/70952817/160518284-27b86109-a7e6-49f1-9e8f-803e259c0e7f.png)

Mockup:
![WhatsApp Image 2022-03-27 at 1 13 11 AM](https://user-images.githubusercontent.com/70952817/160255387-a15cd74f-d961-4322-afb7-b618dc20e286.jpeg)

**Comment by ekkynovrizalam** [comment]
1. tidak ada usecase description

2.acitivity diagram masih salah harus memunculkan interaksi dengan sistem

**Comment by ekkynovrizalam** [comment]
Ini jadinya apa ya activitynya?

**Comment by ftk2000** [comment]
> Ini jadinya apa ya activitynya?

Izin menjawab pak, untuk yang ini activitynya adalah melihat thread apa saja yang sudah dibuka pak, yang tadi bapak minta disatukan saja antara tampilan user dan tampilan adminnya. Ini juga sekaligus jadi laman pertama yang ditampilkan kalau kita memilih menu forum pak.

**Comment by ekkynovrizalam** [comment]
dibuat dinamis ya berarti konten thread nya bukan statis

**Comment by ekkynovrizalam** [comment]
Controller belum bisa

**Comment by y-andella** [comment]
https://user-images.githubusercontent.com/92220462/163794574-e7649044-9989-4417-875d-42944897def0.mp4

Video Demonstrasi PBI4 - Laman Utama forum
