### ISSUE TITLE
[S1-PBI5] Membuat thread forum

### ISSUE THREAD

**Issue by Yukkine** [SI-RPL-2022/SI4303_A_LIVEQUALIE#7]
Membuat thread forum sebagai wadah diskusi para user.

**Comment by Yukkine** [comment]
Berikut merupakan activity diagram dari laman forum :
![Membuat thread forum](https://user-images.githubusercontent.com/70952817/160516214-b0dba8bf-051e-4050-a0f3-d53729b67593.png)

Uscase Description:
![image](https://user-images.githubusercontent.com/70952817/160518882-4e458304-a972-4a53-b323-e73773d1fac4.png)

Mockup:
![ADD FORUM](https://user-images.githubusercontent.com/70952817/160652056-58bb4b63-be2a-4150-8970-c0861948a09d.png)

**Comment by ekkynovrizalam** [comment]
1. tidak ada usecase description

2.acitivity diagram masih salah harus memunculkan interaksi dengan sistem

**Comment by Larasrn** [comment]
https://user-images.githubusercontent.com/92219856/163795061-26d5cdfb-a8a5-4b06-a295-f9ba6e2caead.mp4

Video demonstrasi PBI5 - Membuat thread forum
