### ISSUE TITLE
[S1 - PBI20] Membuat comment forum

### ISSUE THREAD

**Issue by cnchaula** [SI-RPL-2022/SI4303_A_LIVEQUALIE#8]
Membuat comment forum untuk memberikan tanggapan terhadap thread yang ada.

**Comment by Yukkine** [comment]
Berikut merupakan activity diagram dari comment forum :
![Membuat comment forum](https://user-images.githubusercontent.com/70952817/160516355-2f15937f-3ba7-402a-90cc-bb6165b7a1b4.png)

Usecase Description:
![image](https://user-images.githubusercontent.com/70952817/160519921-025236af-60b9-4365-a411-2805a1368f43.png)

Mockup design:
![ADD REPLAY FORUM USER](https://user-images.githubusercontent.com/70952817/160526046-8eed0b61-d8d0-4ea4-a232-52d1a74aa5a1.png)

**Comment by ekkynovrizalam** [comment]
bisa membuat comment, edit comment dan delete comment
