### ISSUE TITLE
[S2 - PBI6] Membuat laman donasi

### ISSUE THREAD

**Issue by cnchaula** [SI-RPL-2022/SI4303_A_LIVEQUALIE#9]
Laman donasi Admin digunakan oleh Admin untuk melihat jumlah donasi yang masuk.

**Comment by cnchaula** [comment]
Activity Diagram:
![ActivityDonasiAdmin drawio](https://user-images.githubusercontent.com/92134925/165122737-6cbae95f-945a-4b91-a938-b3502c9d0af8.png)

Usecase Description:
<img width="377" alt="pbi7 desc" src="https://user-images.githubusercontent.com/92134925/165123015-ba56ba86-62fe-447e-9458-505b986e2082.png">

Mockup:
![Donasi Page Admin](https://user-images.githubusercontent.com/92134925/165123313-5d618c9a-13f1-4ece-b3a3-d02e23ac55a6.png)

**Comment by ekkynovrizalam** [comment]
Issue #13 dijadikan satu PBI dengan PBI ini. trus di tambahkan fitur download atau view bukti transfer

**Comment by ftk2000** [comment]
Video Demo PBI6
https://user-images.githubusercontent.com/92095441/170887564-a187185b-0a55-49a6-a5db-5e55cbfb4c96.mp4

**Comment by ekkynovrizalam** [comment]
video tidak bisa dibuka

**Comment by ftk2000** [comment]
Revisi Video Demi PBI6

https://user-images.githubusercontent.com/92095441/178173603-d237ed32-7279-4a2f-ab6e-11ba48bc4852.mp4
